import { Restaurant, Category } from './types';

export const restaurant: Restaurant = {
  name: 'Flame & Dough',
  coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=675&fit=crop',
  logo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=200&h=200&fit=crop',
  isOpen: true,
  opensAt: '11:00',
  prepTime: '25–35 min',
  minOrder: 150,
  deliveryFee: 15,
  deliveryAvailable: true,
  pickupAvailable: true,
  location: {
    address: 'Bağdat Cad. No:123, Kadıköy, İstanbul',
    lat: 40.9808,
    lng: 29.0562,
  },
  districts: [
    'Kadıköy',
    'Üsküdar',
    'Ataşehir',
    'Maltepe',
    'Beşiktaş',
    'Şişli',
    'Beyoğlu',
    'Bakırköy',
    'Fatih',
    'Kartal',
    'Pendik',
    'Tuzla',
    'Sarıyer',
    'Eyüpsultan',
    'Zeytinburnu',
  ],
};

export const categories: Category[] = [
  {
    id: 'popular',
    name: 'Popular Items',
    description: 'Our customers\' favourites',
    items: [
      {
        id: 'classic-burger',
        name: 'Classic Smash Burger',
        description: 'Double-smashed beef patty, American cheese, caramelised onions, house sauce, brioche bun',
        price: 145,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 10,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Onion', 'Pickles', 'Lettuce', 'Tomato', 'House Sauce', 'American Cheese'],
          },
          {
            type: 'single',
            name: 'Patty Doneness',
            required: true,
            options: [
              { id: 'medium', name: 'Medium', priceDelta: 0 },
              { id: 'medium-well', name: 'Medium-Well', priceDelta: 0 },
              { id: 'well-done', name: 'Well Done', priceDelta: 0 },
            ],
          },
          {
            type: 'multi',
            name: 'Extra Toppings',
            minSelections: 0,
            maxSelections: 3,
            options: [
              { id: 'extra-cheese', name: 'Extra Cheese', priceDelta: 15 },
              { id: 'bacon', name: 'Crispy Bacon', priceDelta: 25 },
              { id: 'jalapeno', name: 'Jalapeño', priceDelta: 10 },
              { id: 'avocado', name: 'Avocado', priceDelta: 20 },
              { id: 'egg', name: 'Fried Egg', priceDelta: 15 },
            ],
          },
        ],
      },
      {
        id: 'margherita-pizza',
        name: 'Margherita Pizza',
        description: 'San Marzano tomato sauce, fresh mozzarella, basil leaves, extra-virgin olive oil',
        price: 130,
        image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=600&h=450&fit=crop',
        tags: ['vegan'],
        soldOut: false,
        maxQuantity: 10,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Basil', 'Olive Oil', 'Garlic'],
          },
          {
            type: 'single',
            name: 'Size',
            required: true,
            options: [
              { id: 'small', name: 'Small (25cm)', priceDelta: 0 },
              { id: 'medium', name: 'Medium (30cm)', priceDelta: 30 },
              { id: 'large', name: 'Large (35cm)', priceDelta: 55 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'burgers',
    name: 'Burgers',
    description: 'Hand-smashed daily, served on toasted brioche',
    items: [
      {
        id: 'classic-burger-2',
        name: 'Classic Smash Burger',
        description: 'Double-smashed beef patty, American cheese, caramelised onions, house sauce, brioche bun',
        price: 145,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 10,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Onion', 'Pickles', 'Lettuce', 'Tomato', 'House Sauce', 'American Cheese'],
          },
          {
            type: 'single',
            name: 'Patty Doneness',
            required: true,
            options: [
              { id: 'medium', name: 'Medium', priceDelta: 0 },
              { id: 'medium-well', name: 'Medium-Well', priceDelta: 0 },
              { id: 'well-done', name: 'Well Done', priceDelta: 0 },
            ],
          },
          {
            type: 'multi',
            name: 'Extra Toppings',
            minSelections: 0,
            maxSelections: 3,
            options: [
              { id: 'extra-cheese', name: 'Extra Cheese', priceDelta: 15 },
              { id: 'bacon', name: 'Crispy Bacon', priceDelta: 25 },
              { id: 'jalapeno', name: 'Jalapeño', priceDelta: 10 },
              { id: 'avocado', name: 'Avocado', priceDelta: 20 },
              { id: 'egg', name: 'Fried Egg', priceDelta: 15 },
            ],
          },
        ],
      },
      {
        id: 'spicy-chicken',
        name: 'Spicy Chicken Burger',
        description: 'Crispy fried chicken thigh, spicy mayo, coleslaw, pickled jalapeño, sesame bun',
        price: 135,
        image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&h=450&fit=crop',
        tags: ['spicy'],
        soldOut: false,
        maxQuantity: 10,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Spicy Mayo', 'Coleslaw', 'Jalapeño', 'Lettuce'],
          },
          {
            type: 'multi',
            name: 'Extras',
            minSelections: 0,
            maxSelections: 2,
            options: [
              { id: 'extra-sauce', name: 'Extra Spicy Mayo', priceDelta: 10 },
              { id: 'cheese-slice', name: 'Cheese Slice', priceDelta: 15 },
              { id: 'onion-rings', name: 'Onion Rings', priceDelta: 20 },
            ],
          },
        ],
      },
      {
        id: 'mushroom-swiss',
        name: 'Mushroom Swiss Burger',
        description: 'Beef patty, sautéed mushrooms, Swiss cheese, garlic aioli, arugula',
        price: 155,
        image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&h=450&fit=crop',
        tags: [],
        soldOut: true,
        maxQuantity: 10,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Mushrooms', 'Swiss Cheese', 'Garlic Aioli', 'Arugula'],
          },
        ],
      },
      {
        id: 'veggie-burger',
        name: 'Veggie Burger',
        description: 'House-made black bean patty, avocado, roasted peppers, vegan mayo, whole wheat bun',
        price: 120,
        image: 'https://images.unsplash.com/photo-1520072959219-c595e6cdc07a?w=600&h=450&fit=crop',
        tags: ['vegan', 'gluten-free'],
        soldOut: false,
        maxQuantity: 10,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Avocado', 'Roasted Peppers', 'Vegan Mayo', 'Lettuce'],
          },
        ],
      },
    ],
  },
  {
    id: 'pizzas',
    name: 'Pizzas',
    description: 'Stone-oven baked, Neapolitan style',
    items: [
      {
        id: 'margherita',
        name: 'Margherita',
        description: 'San Marzano tomato, fresh mozzarella, basil, olive oil',
        price: 130,
        image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=600&h=450&fit=crop',
        tags: ['vegan'],
        soldOut: false,
        maxQuantity: 5,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Basil', 'Olive Oil', 'Garlic'],
          },
          {
            type: 'single',
            name: 'Size',
            required: true,
            options: [
              { id: 'small', name: 'Small (25cm)', priceDelta: 0 },
              { id: 'medium', name: 'Medium (30cm)', priceDelta: 30 },
              { id: 'large', name: 'Large (35cm)', priceDelta: 55 },
            ],
          },
        ],
      },
      {
        id: 'pepperoni',
        name: 'Pepperoni',
        description: 'Tomato sauce, mozzarella, spicy pepperoni, oregano',
        price: 150,
        image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&h=450&fit=crop',
        tags: ['spicy'],
        soldOut: false,
        maxQuantity: 5,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Oregano', 'Pepperoni'],
          },
          {
            type: 'single',
            name: 'Size',
            required: true,
            options: [
              { id: 'small', name: 'Small (25cm)', priceDelta: 0 },
              { id: 'medium', name: 'Medium (30cm)', priceDelta: 30 },
              { id: 'large', name: 'Large (35cm)', priceDelta: 55 },
            ],
          },
          {
            type: 'multi',
            name: 'Add Toppings',
            minSelections: 0,
            maxSelections: 4,
            options: [
              { id: 'mushroom', name: 'Mushroom', priceDelta: 15 },
              { id: 'olive', name: 'Black Olive', priceDelta: 10 },
              { id: 'pepper', name: 'Green Pepper', priceDelta: 10 },
              { id: 'onion', name: 'Red Onion', priceDelta: 10 },
              { id: 'corn', name: 'Sweet Corn', priceDelta: 10 },
            ],
          },
        ],
      },
      {
        id: 'four-cheese',
        name: 'Four Cheese',
        description: 'Mozzarella, gorgonzola, parmesan, goat cheese, honey drizzle',
        price: 165,
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 5,
        modifierGroups: [
          {
            type: 'single',
            name: 'Size',
            required: true,
            options: [
              { id: 'small', name: 'Small (25cm)', priceDelta: 0 },
              { id: 'medium', name: 'Medium (30cm)', priceDelta: 30 },
              { id: 'large', name: 'Large (35cm)', priceDelta: 55 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'sides',
    name: 'Sides',
    items: [
      {
        id: 'fries',
        name: 'Crispy Fries',
        description: 'Hand-cut potatoes, sea salt, served with ketchup and mayo',
        price: 45,
        image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&h=450&fit=crop',
        tags: ['vegan', 'gluten-free'],
        soldOut: false,
        maxQuantity: 10,
        modifierGroups: [
          {
            type: 'single',
            name: 'Sauce',
            required: false,
            options: [
              { id: 'ketchup', name: 'Ketchup', priceDelta: 0 },
              { id: 'mayo', name: 'Mayonnaise', priceDelta: 0 },
              { id: 'bbq', name: 'BBQ Sauce', priceDelta: 5 },
              { id: 'ranch', name: 'Ranch', priceDelta: 5 },
            ],
            defaultOptionId: 'ketchup',
          },
        ],
      },
      {
        id: 'onion-rings',
        name: 'Onion Rings',
        description: 'Beer-battered thick-cut onion rings, served with chipotle dip',
        price: 55,
        image: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 10,
        modifierGroups: [],
      },
      {
        id: 'caesar-salad',
        name: 'Caesar Salad',
        description: 'Romaine lettuce, parmesan, croutons, house Caesar dressing',
        price: 65,
        image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 10,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Croutons', 'Parmesan', 'Caesar Dressing'],
          },
        ],
      },
      {
        id: 'mozzarella-sticks',
        name: 'Mozzarella Sticks',
        description: 'Breaded mozzarella sticks with marinara dipping sauce',
        price: 60,
        image: 'https://images.unsplash.com/photo-1548340748-6d2b7d7da280?w=600&h=450&fit=crop',
        tags: [],
        soldOut: true,
        maxQuantity: 10,
        modifierGroups: [],
      },
    ],
  },
  {
    id: 'drinks',
    name: 'Drinks',
    items: [
      {
        id: 'cola',
        name: 'Cola',
        description: 'Ice-cold 330ml can',
        price: 20,
        image: 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 20,
        modifierGroups: [],
      },
      {
        id: 'lemonade',
        name: 'Fresh Lemonade',
        description: 'House-squeezed lemonade with fresh mint',
        price: 35,
        image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600&h=450&fit=crop',
        tags: ['vegan'],
        soldOut: false,
        maxQuantity: 20,
        modifierGroups: [
          {
            type: 'single',
            name: 'Sweetness',
            required: false,
            options: [
              { id: 'regular', name: 'Regular', priceDelta: 0 },
              { id: 'less', name: 'Less Sugar', priceDelta: 0 },
              { id: 'none', name: 'No Sugar', priceDelta: 0 },
            ],
            defaultOptionId: 'regular',
          },
        ],
      },
      {
        id: 'ayran',
        name: 'Ayran',
        description: 'Traditional Turkish yogurt drink, 300ml',
        price: 15,
        image: 'https://images.unsplash.com/photo-1588710920985-d7e8c517ba61?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 20,
        modifierGroups: [],
      },
      {
        id: 'iced-tea',
        name: 'Iced Tea',
        description: 'Peach or lemon iced tea, 330ml',
        price: 25,
        image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 20,
        modifierGroups: [
          {
            type: 'single',
            name: 'Flavour',
            required: true,
            options: [
              { id: 'peach', name: 'Peach', priceDelta: 0 },
              { id: 'lemon', name: 'Lemon', priceDelta: 0 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'desserts',
    name: 'Desserts',
    items: [
      {
        id: 'brownie',
        name: 'Chocolate Brownie',
        description: 'Warm chocolate brownie with vanilla ice cream and chocolate sauce',
        price: 65,
        image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 10,
        modifierGroups: [
          {
            type: 'removal',
            name: 'Remove Ingredients',
            ingredients: ['Ice Cream', 'Chocolate Sauce', 'Whipped Cream'],
          },
        ],
      },
      {
        id: 'kunefe',
        name: 'Künefe',
        description: 'Traditional Turkish cheese pastry soaked in sweet syrup, served hot with pistachios',
        price: 85,
        image: 'https://images.unsplash.com/photo-1598110750624-207050c4f28c?w=600&h=450&fit=crop',
        tags: [],
        soldOut: false,
        maxQuantity: 5,
        modifierGroups: [
          {
            type: 'multi',
            name: 'Extras',
            minSelections: 0,
            maxSelections: 2,
            options: [
              { id: 'ice-cream', name: 'Vanilla Ice Cream', priceDelta: 15 },
              { id: 'extra-pistachio', name: 'Extra Pistachio', priceDelta: 10 },
              { id: 'kaymak', name: 'Kaymak (Clotted Cream)', priceDelta: 20 },
            ],
          },
        ],
      },
    ],
  },
];
